/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArtistsInLine: typeof import('./src/components/ArtistsInLine.vue')['default']
    ButtonIcon: typeof import('./src/components/ButtonIcon.vue')['default']
    CatsPanel: typeof import('./src/components/CatsPanel.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    Cover: typeof import('./src/components/Cover.vue')['default']
    CoverRow: typeof import('./src/components/CoverRow.vue')['default']
    MessageBox: typeof import('./src/components/MessageBox/index.vue')['default']
    MvList: typeof import('./src/components/MvList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    TrackList: typeof import('./src/components/TrackList.vue')['default']
    TrackListItem: typeof import('./src/components/TrackListItem.vue')['default']
  }
}
